name: JdkInstall

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: windows-latest # 실행할 runner 환경 지정
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Merge commit message
      run: |
        git log -1 --pretty=%B > message.txt
        echo "::set-output name=message::$(Get-Content message.txt)"
      id: merge_message
      # 최신 커밋 메시지를 추출하고 output 변수에 저장합니다.

    - name: Build and Test
      if: startsWith(steps.merge_message.outputs.message, 'Release')
      run: |
        cd CSharpTest
        dotnet build CSharpTest.sln
        dotnet test ./UnitTestProject1/UnitTestProject1.csproj
      # 'Release'로 시작하는 커밋 메시지를 가진 경우에만 빌드 및 테스트를 수행합니다.

    - name: Get Release Version
      if: startsWith(steps.merge_message.outputs.message, 'Release') && job.status == 'success'
      run: |
        echo "::set-output name=version::$(("${{steps.merge_message.outputs.message}}" -replace 'Release ', ''))"
      id: extract_release_version
      # 'Release'로 시작하는 커밋 메시지를 가지고 성공적으로 빌드되었을 때, 버전 정보를 추출하여 output 변수에 저장합니다.

    - name: Create release tag
      if: startsWith(steps.merge_message.outputs.message, 'Release') && job.status == 'success'
      uses: actions/create-release@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.extract_release_version.outputs.version }}
        release_name: Release ${{ steps.extract_release_version.outputs.version }} v${{ github.run_number }}
        body: ${{ steps.merge_message.outputs.message }}
        draft: false
        prerelease: false
      # 'Release'로 시작하는 커밋 메시지를 가지고 성공적으로 빌드되었을 때, GitHub에 릴리즈 태그를 생성합니다.
